spring.application.name=mates-ecommerce
server.port=4002
spring.datasource.url=jdbc:mysql://localhost:3306/mates_ecommerce
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=MelanieMysql17


spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

application.security.jwt.secretKey=b43e6c05bfebd5dad60136c557ee2582d9335450586f426d6f86862acfa6bc39880fd43f23ae22cc4017b1e7ca9ca3d7dd2d9b6bdb6b7e0697f7047a0652bd9c
application.security.jwt.expiration=86400000
